XmlGenGUI/Models/SOGenXmlPageModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace XmlGenGUI.Models
{
    public class SOGenXmlPageModel
    {
    }
}

XmlGenGUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace XmlGenGUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        

    }
}

XmlGenGUI/Controllers/SOGenController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MtsXmlGenerator;

namespace XmlGenGUI.Controllers
{
    public class SOGenController : Controller
    {
        public ActionResult SOGenXmlPage()
        {

            ViewBag.Message = "Service Order XML Generation";
            Debug.Write("SOGenController:Load!\n");
            return View();
        }
        
        public ActionResult ButtonSubmitClick( string nmi, string checkSum, string toDrop, string fromDrop )
        {
            Debug.Write("SOGenController:Click!\n");
            Payloads.setUpPayloads( nmi, checkSum, toDrop, fromDrop );
            ServiceOrder.setUpServiceOrder(nmi, checkSum, toDrop, fromDrop);
            return View("SOGenXmlPage");
        }
        /*
        public FileResult Download( string FileId )
        {
            int CurrentFileID = Convert.ToInt32(FileId);
            string CurrentFileName = "";

            string contentType = "application/xml";
            
                return File( , contentType, );
        }*/


    }
}

XmlGenGUI/Views/SOGen/ButtonSubmitClick.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ButtonSubmitClick</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

XmlGenGUI/Views/SOGen/SOGenXMLPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title></title>
</head>
<body>
    <form method="post" action="@Url.Action("ButtonSubmitClick", "SOGen")" >
    <h1 style="text-align: center;"><span style="color: #045fb4;">Service Order XML Generator</span></h1>

    <table id="table1">
        <tr>
            <td>NMI:</td>
            <td> <input id="nmi" name="nmi" type="text" runat="server" required placeholder="Enter a Valid NMI" pattern="[A-Za-z0-9]{10,10}" title="NMI should be 10 characters long"/> </td>
        </tr>
        <tr>
            <td>Checksum:</td>
            <td><input id="checkSum" name="checkSum" type="number" runat="server" required min="0" max="9"/></td>
        </tr>
        <tr>
            <td>
                To: 
                <select id="toDrop" name="toDrop" runat="server">
                    <option value="POWERCOR">Powercor</option>
                    <option value="POWCP">PowCP</option>
                </select>
            </td>
            <td>
                From:
                <select id="fromDrop" name="fromDrop" runat="server">
                    <option value="POWERCOR">Powercor</option>
                    <option value="POWCP">PowCP</option>
                </select>
            </td>
        </tr>
    </table>
    <br />

    <div style="text-align: center;">
        <input type="submit" value="Generate XML" />
    </div>
    </form>
</body>
</html>